# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install -qq libboost-all-dev

script: make -ek && make test
